# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 634)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saveImageButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveImageButton.setGeometry(QtCore.QRect(590, 10, 191, 29))
        self.saveImageButton.setObjectName("saveImageButton")
        self.consoleOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.consoleOutput.setGeometry(QtCore.QRect(20, 480, 761, 101))
        self.consoleOutput.setStyleSheet("background-color: #2b2b2b;\n"
"color: rgb(255, 110, 112);   \n"
"font-weight: bold;\n"
"")
        self.consoleOutput.setObjectName("consoleOutput")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(380, 50, 401, 421))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.imageSpace = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.imageSpace.setGeometry(QtCore.QRect(0, 0, 401, 421))
        self.imageSpace.setObjectName("imageSpace")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(21, 11, 351, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openButton = QtWidgets.QPushButton(parent=self.widget)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.widget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.runButton = QtWidgets.QPushButton(parent=self.widget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.textEditor = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.textEditor.setGeometry(QtCore.QRect(21, 49, 351, 421))
        self.textEditor.setObjectName("textEditor")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveImageButton.setText(_translate("MainWindow", "Save Image"))
        self.consoleOutput.setText(_translate("MainWindow", "Console Output"))
        self.imageSpace.setText(_translate("MainWindow", "   "))
        self.openButton.setText(_translate("MainWindow", "Open File"))
        self.saveButton.setText(_translate("MainWindow", "Save File"))
        self.runButton.setText(_translate("MainWindow", "Run"))
